In [1]:
import numpy as np
from sklearn import linear_model
import time

In [2]:
n_samples, n_features = 1, 500

x = np.random.randn(n_samples, n_features)
y = np.random.randn(n_samples)

In [3]:
x

array([[ 2.50395083e-01, -9.93664726e-01, -3.54353690e-01,
         1.48088879e+00,  7.53070635e-01, -4.09814878e-01,
        -2.31013378e-01,  8.89744109e-01, -8.43428446e-01,
        -4.73157449e-01, -2.65102709e-01, -4.54507691e-01,
        -1.83101614e-01,  1.34133283e+00,  4.79137075e-01,
        -6.83898750e-01,  1.91273676e+00, -5.65062217e-02,
         1.28912191e+00,  2.32279620e-01,  6.48475700e-01,
         3.03881389e-01,  4.87394089e-01, -1.82316380e+00,
         6.45743854e-01,  4.56630138e-01, -6.53443908e-01,
        -1.31945497e+00,  2.63148873e-01, -4.80577196e-01,
        -9.35959660e-02, -9.97392070e-01,  2.90928679e-01,
        -9.19744869e-01, -5.78313001e-01,  1.00169049e+00,
        -9.78599225e-01, -3.61673784e-01,  2.01506236e+00,
        -9.43429417e-01,  6.45232417e-01,  2.37602697e-01,
        -3.16057232e-01, -5.70238167e-01, -5.42727411e-01,
        -1.73256348e-01, -1.31888980e+00,  5.18650040e-01,
         2.50108140e-01,  5.15225748e-01,  1.72103988e+0

In [4]:
x.shape

(1, 500)

In [5]:
y

array([-1.82840195])

In [6]:
model = linear_model.SGDRegressor()

In [7]:
start_time = time.time()

model.partial_fit(X=x, y=y)

elapsed_time = time.time() - start_time

print(elapsed_time)

0.0019943714141845703


In [8]:
x2 = np.random.randn(n_samples, n_features)
y2 = np.random.randn(n_samples)

In [9]:
model.partial_fit(X=x, y=y)

SGDRegressor()

### Demo test for undersanding

In [10]:
np.random.randn(5)

array([ 0.06310734, -1.86803546, -0.36498248,  0.64204474, -0.07431086])

In [11]:
np.random.randn(5, 5)

array([[-0.6250356 ,  0.55564371,  0.52399762,  0.08609455, -0.34973785],
       [-0.070434  ,  0.87846315,  2.4856685 , -0.53253672, -2.70779763],
       [-0.4265912 , -0.31243985,  2.54571165,  1.53873705, -0.38482718],
       [ 0.38787382,  0.00417585, -1.96303484,  1.55210428, -0.34255808],
       [ 1.36806897,  0.12294734, -0.85522047, -1.34824055, -0.20812927]])

In [12]:
np.random.randn(3,3,2)

array([[[-0.63146137, -0.73200907],
        [-0.63036279,  0.24913651],
        [ 0.54532791,  0.60788071]],

       [[-0.25198782, -1.03368535],
        [ 0.49209055, -0.19924517],
        [ 3.09133828, -0.90420715]],

       [[ 1.01540595,  0.37100095],
        [ 0.38295522,  1.34932395],
        [-0.43776268,  1.27286111]]])